language: node_js
node_js:
  - 8

script:
  - yarn check
  - yarn run generate

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: out
  target_branch: master
  on:
    branch: develop
